[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.16"
fastapi = "^0.94.1"
mangum = "^0.17.0"

[tool.poetry.group.development.dependencies]
uvicorn = "^0.21.1"
